spring.application.name=ticket-booking-app
spring.security.user.name=user

spring.security.user.password=${SECURITY_USER_PASSWORD}
app.security.jwt-secret=${JWT_SECRET}

spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_booking_db
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD}