spring.application.name= ticket-booking-app

spring.security.user.name= user
spring.security.user.password= ${SECURITY_USER_PASSWORD}

app.security.jwt-secret= ${JWT_SECRET}
app.security.access-token-expiration= ${ACCES_TOKEN_EXPIRATION}
app.security.refresh-token-expiration= ${REFRESH_TOKEN_EXPIRATION}

app.admin.name= Administrator
app.admin.email= ${ADMIN_EMAIL}
app.admin.password= ${ADMIN_PASSWORD}

spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_booking_db
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD}

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false